### ISSUE TITLE
Rename config variables

### ISSUE THREAD

**Issue by cstrangedk** [skalenetwork/metaport#26]
* `schainAliases -> dAppNames`
* `open -> openOnLoad`
* `network -> skaleNetwork (mainnet by default)`
* `schains -> skaleChains`

**Comment by dmytrotkk** [comment]
@cstrangedk 

1. `schainAliases` is now called `chainsMetadata` since it includes additional info, such as `minSfuelWei`, `faucetUrl`, etc.
2. `schains` is renamed to `chains`, since it includes both SKALE Chains and Ethereum Mainnet.
3. `open -> openOnLoad` and `network -> skaleNetwork` - done

Also - going to add interfaces for all Metaport config fields, so it will be easier to find out available config fields.
