### ISSUE TITLE
Widget state does not handle rejected TXs

### ISSUE THREAD

**Issue by JasperGem** [skalenetwork/metaport#51]
`v 0.1.0-develop.1`

**Describe the bug**

* do a TX in metaport
* reject the TX in metamask
* widget logs the rejection in the console but just spins in 'transferring' (for example) forever and does not notice the tx state

![image](https://user-images.githubusercontent.com/86413952/189738589-9cf67b1f-c4c8-4777-9999-2bcfd068a942.png)

**Comment by dmytrotkk** [comment]
@JasperGem this issue is resolved in [0.1.1-develop.0](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.1.1-develop.0)
<img width="421" alt="Screenshot 2022-09-21 at 19 31 36" src="https://user-images.githubusercontent.com/15244591/191583109-8cb7ff03-bdcf-4072-a79d-859f5431beaa.png">

Please, check it out and close the ticket if everything works as expected.
