### ISSUE TITLE
METAPORT User Experience issue

### ISSUE THREAD

**Issue by ebruoguzberk** [skalenetwork/metaport#53]
**Describe the bug**
The second part of the drill-down covers the entire UI. 

**To Reproduce**
1. [ Go to Ruby Exchange ](https://additivefidev.com/profile)
2. Click on the widget: 

3. Select on the top Europa Chain 
<img width="332" alt="Screen Shot 2022-09-14 at 2 58 55 PM" src="https://user-images.githubusercontent.com/52053189/190458488-515da319-6ded-4dcb-aefc-1d64daf79520.png">

4. Go the second drill down and click you will see that drill down covers the entire widget and looks very confusing. 
<img width="321" alt="Screen Shot 2022-09-14 at 2 58 45 PM" src="https://user-images.githubusercontent.com/52053189/190458440-a91544ba-1ed6-493a-aa83-8acfed7d496f.png">

**Expected behavior**
Push the first `drill down` box somewhere at the top of the second drill down.  
<img width="390" alt="Screen Shot 2022-09-15 at 9 53 23 AM" src="https://user-images.githubusercontent.com/52053189/190462884-39058a73-06b4-4f71-83e9-51c52492018d.png">

**Comment by dmytrotkk** [comment]
@ebruoguzberk thanks for trying Metaport and giving your feedback!

As for this issue - it's intentional behavior - all other blocks are hidden when chain selection is open. The issue here is a wrong margin when this section is expanded. 

It's fixed in the latest Metaport version ([0.1.1-develop.0](https://www.npmjs.com/package/@skalenetwork/metaport/v/0.1.1-develop.0)) - you can try it out on the demo website.
