### ISSUE TITLE
Runtime Error when switching networks

### ISSUE THREAD

**Issue by RubyAquaMarine** [skalenetwork/metaport#79]
<img width="358" alt="Screen Shot 2022-11-15 at 3 59 40 PM" src="https://user-images.githubusercontent.com/86425604/201876158-eaa0203c-a48a-47e1-9bca-99e0496ebadb.png">

When switching networks from the MP "Switch transfer direction" button,  there is a runtime error 
<img width="1247" alt="Screen Shot 2022-11-15 at 3 57 14 PM" src="https://user-images.githubusercontent.com/86425604/201876846-889472f4-7a5c-4d73-8af3-952015b1ed8d.png">

"Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced." 

version : ``` "1.0.0-develop.3```

**Comment by dmitry-tk** [comment]
Context:
This error may occur sometimes when networks are switched in Metamask while some processes are running in the background - for example, tokens lookup or sFuel data retrieval

![telegram-cloud-photo-size-2-5449628361602220546-y](https://user-images.githubusercontent.com/15244591/201967944-4237ad3b-be16-4068-91cf-b7d7f1ab6dc0.jpg)

It shouldn't break any functionality, just errors in the console 

Will be fixed by adding try...catch blocks to these parts.
Will be included in MP hotfix release.

CC @PolinaKiporenko
